### ISSUE TITLE
maxVolume is missing or invalid

### ISSUE THREAD

**Issue by CatTail** [typesafehub/cinnamon-ui#35]
I am following https://developer.lightbend.com/docs/cinnamon/current/visualizations/vizceral.html to setup cinnamon-ui on my machine, I successfully send data from my Akka application to kibana, however when I open http://localhost:8080, the DevTool console says

```
vizceral.js:66734 maxVolume is missing or invalid (undefined), but it is required to calculate relative particle density. See https://github.com/Netflix/Vizceral/wiki/How-to-Use#graph-data-format
```

I'm not able to read cinnamon-vizceral-frontend source code because it's close source, can you help to check why it's broken?

![image](https://user-images.githubusercontent.com/1606069/49730936-c426f380-fcb4-11e8-9697-5655e678c002.png)

**Comment by henrikengstrom** [comment]
Hi @CatTail. Apologies for the late reply.

The warning you see does not have to do with the data missing or not. I have seen the same warning when running Vizceral and Cinnamon successfully. Have you enabled the experimental flag, `experimental.connections = true`, to ensure that data is created?  https://developer.lightbend.com/docs/cinnamon/current/visualizations/vizceral.html#configuring-cinnamon

If that doesn't solve the issue I suggest that you log a support ticket in our customer support tool (should you be a customer?) and we will take it from there.
